name: budgetti
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  nanoid2: ^2.0.1
  path: ^1.9.1
  provider: ^6.1.4
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: true
  image_path_android: "assets/icons/android/mipmap-xxxhdpi/ic_launcher.png"
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "assets/icons/icon.png"
  # adaptive_icon_monochrome: true
  # adaptive_icon_foreground_inset: 16
  # min_sdk_android: 21

  ios: true
  image_path_ios: "assets/icons/1024.png"
  # image_path_ios_dark_transparent: "assets/icons/icon.png"
  # image_path_ios_tinted_grayscale: "assets/icons/icon.png"
  # background_color_ios: "#FFFFFF"
  # remove_alpha_ios: true
  # desaturate_tinted_to_grayscale_ios: true
